# Use the official PostgreSQL image as the base
FROM postgres:14

# Set the environment variables for the database
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=Muthuri24
ENV POSTGRES_DB=postgres

# Copy any database initialization scripts or data files
#COPY init/ /docker-entrypoint-initdb.d/