--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2 (Debian 16.2-1.pgdg120+2)
-- Dumped by pg_dump version 16.0

-- Started on 2024-04-15 03:04:23

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3441 (class 1262 OID 25107)
-- Name: lovedmemorydb; Type: DATABASE; Schema: -; Owner: postgres
--
SELECT 'CREATE DATABASE lovedmemorydb'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'lovedmemorydb')\gexec
-- WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE lovedmemorydb OWNER TO postgres;

\connect lovedmemorydb

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 25113)
-- Name: lovedmemory; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA lovedmemory;


ALTER SCHEMA lovedmemory OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 224 (class 1259 OID 25145)
-- Name: aspnetroleclaims; Type: TABLE; Schema: lovedmemory; Owner: postgres
--

CREATE TABLE lovedmemory.aspnetroleclaims (
    id integer NOT NULL,
    roleid text NOT NULL,
    claimtype text,
    claimvalue text
);


ALTER TABLE lovedmemory.aspnetroleclaims OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 25144)
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: lovedmemory; Owner: postgres
--

ALTER TABLE lovedmemory.aspnetroleclaims ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lovedmemory."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 25158)
-- Name: aspnetuserclaims; Type: TABLE; Schema: lovedmemory; Owner: postgres
--

CREATE TABLE lovedmemory.aspnetuserclaims (
    id integer NOT NULL,
    userid text NOT NULL,
    claimtype text,
    claimvalue text
);


ALTER TABLE lovedmemory.aspnetuserclaims OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 25157)
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: lovedmemory; Owner: postgres
--

ALTER TABLE lovedmemory.aspnetuserclaims ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lovedmemory."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 25114)
-- Name: aspnetroles; Type: TABLE; Schema: lovedmemory; Owner: postgres
--

CREATE TABLE lovedmemory.aspnetroles (
    id text NOT NULL,
    name character varying(256),
    normalizedname character varying(256),
    concurrencystamp text
);


ALTER TABLE lovedmemory.aspnetroles OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 25170)
-- Name: aspnetuserlogins; Type: TABLE; Schema: lovedmemory; Owner: postgres
--

CREATE TABLE lovedmemory.aspnetuserlogins (
    loginprovider character varying(128) NOT NULL,
    providerkey character varying(128) NOT NULL,
    providerdisplayname text,
    userid text NOT NULL
);


ALTER TABLE lovedmemory.aspnetuserlogins OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 25182)
-- Name: aspnetuserroles; Type: TABLE; Schema: lovedmemory; Owner: postgres
--

CREATE TABLE lovedmemory.aspnetuserroles (
    userid text NOT NULL,
    roleid text NOT NULL
);


ALTER TABLE lovedmemory.aspnetuserroles OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 25121)
-- Name: aspnetusers; Type: TABLE; Schema: lovedmemory; Owner: postgres
--

CREATE TABLE lovedmemory.aspnetusers (
    id text NOT NULL,
    username character varying(256),
    normalizedusername character varying(256),
    email character varying(256),
    normalizedemail character varying(256),
    emailconfirmed boolean NOT NULL,
    passwordhash text,
    securitystamp text,
    concurrencystamp text,
    phonenumber text,
    phonenumberconfirmed boolean NOT NULL,
    twofactorenabled boolean NOT NULL,
    lockoutend timestamp with time zone,
    lockoutenabled boolean NOT NULL,
    accessfailedcount integer NOT NULL,
    firstname text DEFAULT ''::text NOT NULL,
    lastname text DEFAULT ''::text,
    nickname text DEFAULT ''::text,
    othername text DEFAULT ''::text
);


ALTER TABLE lovedmemory.aspnetusers OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 25199)
-- Name: aspnetusertokens; Type: TABLE; Schema: lovedmemory; Owner: postgres
--

CREATE TABLE lovedmemory.aspnetusertokens (
    userid text NOT NULL,
    loginprovider character varying(128) NOT NULL,
    name character varying(128) NOT NULL,
    value text
);


ALTER TABLE lovedmemory.aspnetusertokens OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 25212)
-- Name: comments; Type: TABLE; Schema: lovedmemory; Owner: postgres
--

CREATE TABLE lovedmemory.comments (
    id integer NOT NULL,
    tributeid integer NOT NULL,
    details text NOT NULL,
    visible boolean NOT NULL,
    dateposted timestamp with time zone NOT NULL,
    parentcommentid integer,
    dateedited timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
    edited boolean DEFAULT false NOT NULL,
    commentid integer
);


ALTER TABLE lovedmemory.comments OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 25211)
-- Name: comments_Id_seq; Type: SEQUENCE; Schema: lovedmemory; Owner: postgres
--

ALTER TABLE lovedmemory.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lovedmemory."comments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 25129)
-- Name: eventdetails; Type: TABLE; Schema: lovedmemory; Owner: postgres
--

CREATE TABLE lovedmemory.eventdetails (
    id integer NOT NULL,
    tributeid integer NOT NULL,
    eventdate timestamp with time zone NOT NULL,
    eventlocation text NOT NULL,
    details text NOT NULL
);


ALTER TABLE lovedmemory.eventdetails OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 25128)
-- Name: eventdetails_Id_seq; Type: SEQUENCE; Schema: lovedmemory; Owner: postgres
--

ALTER TABLE lovedmemory.eventdetails ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lovedmemory."eventdetails_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 25137)
-- Name: tributes; Type: TABLE; Schema: lovedmemory; Owner: postgres
--

CREATE TABLE lovedmemory.tributes (
    id integer NOT NULL,
    viewcount integer NOT NULL,
    name text NOT NULL,
    nickname text NOT NULL,
    slug text NOT NULL,
    ownerid text NOT NULL,
    mainimageurl text NOT NULL,
    edited timestamp with time zone NOT NULL,
    created timestamp with time zone NOT NULL,
    rundate timestamp with time zone NOT NULL,
    active boolean NOT NULL
);


ALTER TABLE lovedmemory.tributes OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 25136)
-- Name: tributes_Id_seq; Type: SEQUENCE; Schema: lovedmemory; Owner: postgres
--

ALTER TABLE lovedmemory.tributes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lovedmemory."tributes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 25108)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 3269 (class 2606 OID 25261)
-- Name: aspnetroleclaims pk_aspnetroleclaims; Type: CONSTRAINT; Schema: lovedmemory; Owner: postgres
--

ALTER TABLE ONLY lovedmemory.aspnetroleclaims
    ADD CONSTRAINT pk_aspnetroleclaims PRIMARY KEY (id);


--
-- TOC entry 3258 (class 2606 OID 25259)
-- Name: aspnetroles pk_aspnetroles; Type: CONSTRAINT; Schema: lovedmemory; Owner: postgres
--

ALTER TABLE ONLY lovedmemory.aspnetroles
    ADD CONSTRAINT pk_aspnetroles PRIMARY KEY (id);


--
-- TOC entry 3272 (class 2606 OID 25257)
-- Name: aspnetuserclaims pk_aspnetuserclaims; Type: CONSTRAINT; Schema: lovedmemory; Owner: postgres
--

ALTER TABLE ONLY lovedmemory.aspnetuserclaims
    ADD CONSTRAINT pk_aspnetuserclaims PRIMARY KEY (id);


--
-- TOC entry 3275 (class 2606 OID 25255)
-- Name: aspnetuserlogins pk_aspnetuserlogins; Type: CONSTRAINT; Schema: lovedmemory; Owner: postgres
--

ALTER TABLE ONLY lovedmemory.aspnetuserlogins
    ADD CONSTRAINT pk_aspnetuserlogins PRIMARY KEY (loginprovider, providerkey);


--
-- TOC entry 3278 (class 2606 OID 25253)
-- Name: aspnetuserroles pk_aspnetuserroles; Type: CONSTRAINT; Schema: lovedmemory; Owner: postgres
--

ALTER TABLE ONLY lovedmemory.aspnetuserroles
    ADD CONSTRAINT pk_aspnetuserroles PRIMARY KEY (userid, roleid);


--
-- TOC entry 3262 (class 2606 OID 25249)
-- Name: aspnetusers pk_aspnetusers; Type: CONSTRAINT; Schema: lovedmemory; Owner: postgres
--

ALTER TABLE ONLY lovedmemory.aspnetusers
    ADD CONSTRAINT pk_aspnetusers PRIMARY KEY (id);


--
-- TOC entry 3280 (class 2606 OID 25251)
-- Name: aspnetusertokens pk_aspnetusertokens; Type: CONSTRAINT; Schema: lovedmemory; Owner: postgres
--

ALTER TABLE ONLY lovedmemory.aspnetusertokens
    ADD CONSTRAINT pk_aspnetusertokens PRIMARY KEY (userid, loginprovider, name);


--
-- TOC entry 3284 (class 2606 OID 25247)
-- Name: comments pk_comments; Type: CONSTRAINT; Schema: lovedmemory; Owner: postgres
--

ALTER TABLE ONLY lovedmemory.comments
    ADD CONSTRAINT pk_comments PRIMARY KEY (id);


--
-- TOC entry 3264 (class 2606 OID 25245)
-- Name: eventdetails pk_eventdetails; Type: CONSTRAINT; Schema: lovedmemory; Owner: postgres
--

ALTER TABLE ONLY lovedmemory.eventdetails
    ADD CONSTRAINT pk_eventdetails PRIMARY KEY (id);


--
-- TOC entry 3266 (class 2606 OID 25243)
-- Name: tributes pk_tributes; Type: CONSTRAINT; Schema: lovedmemory; Owner: postgres
--

ALTER TABLE ONLY lovedmemory.tributes
    ADD CONSTRAINT pk_tributes PRIMARY KEY (id);


--
-- TOC entry 3255 (class 2606 OID 25112)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3259 (class 1259 OID 25234)
-- Name: EmailIndex; Type: INDEX; Schema: lovedmemory; Owner: postgres
--

CREATE INDEX "EmailIndex" ON lovedmemory.aspnetusers USING btree (normalizedemail);


--
-- TOC entry 3267 (class 1259 OID 25229)
-- Name: IX_aspnetroleclaims_roleid; Type: INDEX; Schema: lovedmemory; Owner: postgres
--

CREATE INDEX "IX_aspnetroleclaims_roleid" ON lovedmemory.aspnetroleclaims USING btree (roleid);


--
-- TOC entry 3270 (class 1259 OID 25231)
-- Name: IX_aspnetuserclaims_userid; Type: INDEX; Schema: lovedmemory; Owner: postgres
--

CREATE INDEX "IX_aspnetuserclaims_userid" ON lovedmemory.aspnetuserclaims USING btree (userid);


--
-- TOC entry 3273 (class 1259 OID 25232)
-- Name: IX_aspnetuserlogins_userid; Type: INDEX; Schema: lovedmemory; Owner: postgres
--

CREATE INDEX "IX_aspnetuserlogins_userid" ON lovedmemory.aspnetuserlogins USING btree (userid);


--
-- TOC entry 3276 (class 1259 OID 25233)
-- Name: IX_aspnetuserroles_roleid; Type: INDEX; Schema: lovedmemory; Owner: postgres
--

CREATE INDEX "IX_aspnetuserroles_roleid" ON lovedmemory.aspnetuserroles USING btree (roleid);


--
-- TOC entry 3281 (class 1259 OID 25316)
-- Name: IX_comments_commentid; Type: INDEX; Schema: lovedmemory; Owner: postgres
--

CREATE INDEX "IX_comments_commentid" ON lovedmemory.comments USING btree (commentid);


--
-- TOC entry 3282 (class 1259 OID 25237)
-- Name: IX_comments_tributeid; Type: INDEX; Schema: lovedmemory; Owner: postgres
--

CREATE INDEX "IX_comments_tributeid" ON lovedmemory.comments USING btree (tributeid);


--
-- TOC entry 3256 (class 1259 OID 25230)
-- Name: RoleNameIndex; Type: INDEX; Schema: lovedmemory; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON lovedmemory.aspnetroles USING btree (normalizedname);


--
-- TOC entry 3260 (class 1259 OID 25235)
-- Name: UserNameIndex; Type: INDEX; Schema: lovedmemory; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON lovedmemory.aspnetusers USING btree (normalizedusername);


--
-- TOC entry 3285 (class 2606 OID 25262)
-- Name: aspnetroleclaims fk_aspnetroleclaims_aspnetroles_roleid; Type: FK CONSTRAINT; Schema: lovedmemory; Owner: postgres
--

ALTER TABLE ONLY lovedmemory.aspnetroleclaims
    ADD CONSTRAINT fk_aspnetroleclaims_aspnetroles_roleid FOREIGN KEY (roleid) REFERENCES lovedmemory.aspnetroles(id) ON DELETE CASCADE;


--
-- TOC entry 3286 (class 2606 OID 25267)
-- Name: aspnetuserclaims fk_aspnetuserclaims_aspnetusers_userid; Type: FK CONSTRAINT; Schema: lovedmemory; Owner: postgres
--

ALTER TABLE ONLY lovedmemory.aspnetuserclaims
    ADD CONSTRAINT fk_aspnetuserclaims_aspnetusers_userid FOREIGN KEY (userid) REFERENCES lovedmemory.aspnetusers(id) ON DELETE CASCADE;


--
-- TOC entry 3287 (class 2606 OID 25272)
-- Name: aspnetuserlogins fk_aspnetuserlogins_aspnetusers_userid; Type: FK CONSTRAINT; Schema: lovedmemory; Owner: postgres
--

ALTER TABLE ONLY lovedmemory.aspnetuserlogins
    ADD CONSTRAINT fk_aspnetuserlogins_aspnetusers_userid FOREIGN KEY (userid) REFERENCES lovedmemory.aspnetusers(id) ON DELETE CASCADE;


--
-- TOC entry 3288 (class 2606 OID 25277)
-- Name: aspnetuserroles fk_aspnetuserroles_aspnetroles_roleid; Type: FK CONSTRAINT; Schema: lovedmemory; Owner: postgres
--

ALTER TABLE ONLY lovedmemory.aspnetuserroles
    ADD CONSTRAINT fk_aspnetuserroles_aspnetroles_roleid FOREIGN KEY (roleid) REFERENCES lovedmemory.aspnetroles(id) ON DELETE CASCADE;


--
-- TOC entry 3289 (class 2606 OID 25282)
-- Name: aspnetuserroles fk_aspnetuserroles_aspnetusers_userid; Type: FK CONSTRAINT; Schema: lovedmemory; Owner: postgres
--

ALTER TABLE ONLY lovedmemory.aspnetuserroles
    ADD CONSTRAINT fk_aspnetuserroles_aspnetusers_userid FOREIGN KEY (userid) REFERENCES lovedmemory.aspnetusers(id) ON DELETE CASCADE;


--
-- TOC entry 3290 (class 2606 OID 25287)
-- Name: aspnetusertokens fk_aspnetusertokens_aspnetusers_userid; Type: FK CONSTRAINT; Schema: lovedmemory; Owner: postgres
--

ALTER TABLE ONLY lovedmemory.aspnetusertokens
    ADD CONSTRAINT fk_aspnetusertokens_aspnetusers_userid FOREIGN KEY (userid) REFERENCES lovedmemory.aspnetusers(id) ON DELETE CASCADE;


--
-- TOC entry 3291 (class 2606 OID 25317)
-- Name: comments fk_comments_comments_commentid; Type: FK CONSTRAINT; Schema: lovedmemory; Owner: postgres
--

ALTER TABLE ONLY lovedmemory.comments
    ADD CONSTRAINT fk_comments_comments_commentid FOREIGN KEY (commentid) REFERENCES lovedmemory.comments(id);


--
-- TOC entry 3292 (class 2606 OID 25297)
-- Name: comments fk_comments_tributes_tributeid; Type: FK CONSTRAINT; Schema: lovedmemory; Owner: postgres
--

ALTER TABLE ONLY lovedmemory.comments
    ADD CONSTRAINT fk_comments_tributes_tributeid FOREIGN KEY (tributeid) REFERENCES lovedmemory.tributes(id) ON DELETE CASCADE;


-- Completed on 2024-04-15 03:04:23

--
-- PostgreSQL database dump complete
--

